name: echo_env
# Run this workflow every time a new commit pushed to your repository
on: push
env:
  FOO: bar
  REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: chmod
        run: chmod 777 ./echo_env.sh
      - name: does a thing
        run: ./echo_env.sh
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build
